---
abstract: 'Find Perl module distributions within a directory hierarchy'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-distfind
provides:
  App::distfind:
    file: lib/App/distfind.pm
    version: 1.101400
recommends: {}
requires:
  File::Find: 0
  Getopt::Long: 0
  Pod::Usage: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-distfind
  homepage: http://search.cpan.org/dist/App-distfind/
  repository: http://github.com/hanekomu/App-distfind
version: 1.101400
